sudo: false
os:
 - linux
 - osx
language: d
d:
 - dmd
 - ldc
 - dmd-2.084.0
 - ldc-1.13.0
env:
 - ARCH="x86_64" CONF="-sse42"
 - ARCH="x86_64" CONF=""
matrix:
  include:
    - {os: linux, env: ARCH="AARCH64" CONF="", services: docker}
    - {os: linux, d: dmd-2.084.0, env: ARCH="x86" CONF="", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: ldc-1.13.0, env: ARCH="x86" CONF="", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: ldc-1.13.0, env: ARCH="x86" CONF="-sse42", addons: {apt: {packages: [[gcc-multilib]]}}}
branches:
  only:
    - master
script: bash -e test_travis.sh
after_success:
 - bash <(curl -s https://codecov.io/bash)
